package com.jotunheim.thor.dao;

import com.jotunheim.thor.domain.ClientAccessKey;
import com.jotunheim.thor.domain.ClientAccessKeyExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface ClientAccessKeyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client_access_key
     *
     * @mbggenerated Thu Oct 20 19:39:59 CST 2016
     */
    int countByExample(ClientAccessKeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client_access_key
     *
     * @mbggenerated Thu Oct 20 19:39:59 CST 2016
     */
    int deleteByExample(ClientAccessKeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client_access_key
     *
     * @mbggenerated Thu Oct 20 19:39:59 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client_access_key
     *
     * @mbggenerated Thu Oct 20 19:39:59 CST 2016
     */
    int insert(ClientAccessKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client_access_key
     *
     * @mbggenerated Thu Oct 20 19:39:59 CST 2016
     */
    int insertSelective(ClientAccessKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client_access_key
     *
     * @mbggenerated Thu Oct 20 19:39:59 CST 2016
     */
    List<ClientAccessKey> selectByExample(ClientAccessKeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client_access_key
     *
     * @mbggenerated Thu Oct 20 19:39:59 CST 2016
     */
    ClientAccessKey selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client_access_key
     *
     * @mbggenerated Thu Oct 20 19:39:59 CST 2016
     */
    int updateByExampleSelective(@Param("record") ClientAccessKey record, @Param("example") ClientAccessKeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client_access_key
     *
     * @mbggenerated Thu Oct 20 19:39:59 CST 2016
     */
    int updateByExample(@Param("record") ClientAccessKey record, @Param("example") ClientAccessKeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client_access_key
     *
     * @mbggenerated Thu Oct 20 19:39:59 CST 2016
     */
    int updateByPrimaryKeySelective(ClientAccessKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client_access_key
     *
     * @mbggenerated Thu Oct 20 19:39:59 CST 2016
     */
    int updateByPrimaryKey(ClientAccessKey record);
}