package com.jotunheim.thor.dao;

import com.jotunheim.thor.domain.User;
import com.jotunheim.thor.domain.UserExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface UserMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table user
     * @mbggenerated  Thu Oct 20 15:31:19 CST 2016
     */
    int countByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table user
     * @mbggenerated  Thu Oct 20 15:31:19 CST 2016
     */
    int deleteByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table user
     * @mbggenerated  Thu Oct 20 15:31:19 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table user
     * @mbggenerated  Thu Oct 20 15:31:19 CST 2016
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table user
     * @mbggenerated  Thu Oct 20 15:31:19 CST 2016
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table user
     * @mbggenerated  Thu Oct 20 15:31:19 CST 2016
     */
    List<User> selectByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table user
     * @mbggenerated  Thu Oct 20 15:31:19 CST 2016
     */
    User selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table user
     * @mbggenerated  Thu Oct 20 15:31:19 CST 2016
     */
    int updateByExampleSelective(@Param("record") User record,
            @Param("example") UserExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table user
     * @mbggenerated  Thu Oct 20 15:31:19 CST 2016
     */
    int updateByExample(@Param("record") User record,
            @Param("example") UserExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table user
     * @mbggenerated  Thu Oct 20 15:31:19 CST 2016
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table user
     * @mbggenerated  Thu Oct 20 15:31:19 CST 2016
     */
    int updateByPrimaryKey(User record);
}