package com.jotunheim.thor.domain;

import java.util.Date;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.ID
     *
     * @mbggenerated Thu Oct 20 15:31:19 CST 2016
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.NAME
     *
     * @mbggenerated Thu Oct 20 15:31:19 CST 2016
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.PASSWORD
     *
     * @mbggenerated Thu Oct 20 15:31:19 CST 2016
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.NICKNAME
     *
     * @mbggenerated Thu Oct 20 15:31:19 CST 2016
     */
    private String nickname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.REG_TIME
     *
     * @mbggenerated Thu Oct 20 15:31:19 CST 2016
     */
    private Date regTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.UPDATE_TIME
     *
     * @mbggenerated Thu Oct 20 15:31:19 CST 2016
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.LAST_LOGIN_TIME
     *
     * @mbggenerated Thu Oct 20 15:31:19 CST 2016
     */
    private Date lastLoginTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.PHONENUMBER
     *
     * @mbggenerated Thu Oct 20 15:31:19 CST 2016
     */
    private String phonenumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.EMAIL
     *
     * @mbggenerated Thu Oct 20 15:31:19 CST 2016
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.STATUS
     *
     * @mbggenerated Thu Oct 20 15:31:19 CST 2016
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.TOKEN
     *
     * @mbggenerated Thu Oct 20 15:31:19 CST 2016
     */
    private String token;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.LOCATION_ID
     *
     * @mbggenerated Thu Oct 20 15:31:19 CST 2016
     */
    private String locationId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.CITY
     *
     * @mbggenerated Thu Oct 20 15:31:19 CST 2016
     */
    private String city;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.DISTRICT
     *
     * @mbggenerated Thu Oct 20 15:31:19 CST 2016
     */
    private String district;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.ADDRESS
     *
     * @mbggenerated Thu Oct 20 15:31:19 CST 2016
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.COUNTRY
     *
     * @mbggenerated Thu Oct 20 15:31:19 CST 2016
     */
    private String country;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.AVATAR
     *
     * @mbggenerated Thu Oct 20 15:31:19 CST 2016
     */
    private String avatar;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.REAL_NAME
     *
     * @mbggenerated Thu Oct 20 15:31:19 CST 2016
     */
    private String realName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.ROLE_ID
     *
     * @mbggenerated Thu Oct 20 15:31:19 CST 2016
     */
    private Long roleId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.ID
     *
     * @return the value of user.ID
     *
     * @mbggenerated Thu Oct 20 15:31:19 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.ID
     *
     * @param id the value for user.ID
     *
     * @mbggenerated Thu Oct 20 15:31:19 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.NAME
     *
     * @return the value of user.NAME
     *
     * @mbggenerated Thu Oct 20 15:31:19 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.NAME
     *
     * @param name the value for user.NAME
     *
     * @mbggenerated Thu Oct 20 15:31:19 CST 2016
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.PASSWORD
     *
     * @return the value of user.PASSWORD
     *
     * @mbggenerated Thu Oct 20 15:31:19 CST 2016
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.PASSWORD
     *
     * @param password the value for user.PASSWORD
     *
     * @mbggenerated Thu Oct 20 15:31:19 CST 2016
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.NICKNAME
     *
     * @return the value of user.NICKNAME
     *
     * @mbggenerated Thu Oct 20 15:31:19 CST 2016
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.NICKNAME
     *
     * @param nickname the value for user.NICKNAME
     *
     * @mbggenerated Thu Oct 20 15:31:19 CST 2016
     */
    public void setNickname(String nickname) {
        this.nickname = nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.REG_TIME
     *
     * @return the value of user.REG_TIME
     *
     * @mbggenerated Thu Oct 20 15:31:19 CST 2016
     */
    public Date getRegTime() {
        return regTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.REG_TIME
     *
     * @param regTime the value for user.REG_TIME
     *
     * @mbggenerated Thu Oct 20 15:31:19 CST 2016
     */
    public void setRegTime(Date regTime) {
        this.regTime = regTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.UPDATE_TIME
     *
     * @return the value of user.UPDATE_TIME
     *
     * @mbggenerated Thu Oct 20 15:31:19 CST 2016
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.UPDATE_TIME
     *
     * @param updateTime the value for user.UPDATE_TIME
     *
     * @mbggenerated Thu Oct 20 15:31:19 CST 2016
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.LAST_LOGIN_TIME
     *
     * @return the value of user.LAST_LOGIN_TIME
     *
     * @mbggenerated Thu Oct 20 15:31:19 CST 2016
     */
    public Date getLastLoginTime() {
        return lastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.LAST_LOGIN_TIME
     *
     * @param lastLoginTime the value for user.LAST_LOGIN_TIME
     *
     * @mbggenerated Thu Oct 20 15:31:19 CST 2016
     */
    public void setLastLoginTime(Date lastLoginTime) {
        this.lastLoginTime = lastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.PHONENUMBER
     *
     * @return the value of user.PHONENUMBER
     *
     * @mbggenerated Thu Oct 20 15:31:19 CST 2016
     */
    public String getPhonenumber() {
        return phonenumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.PHONENUMBER
     *
     * @param phonenumber the value for user.PHONENUMBER
     *
     * @mbggenerated Thu Oct 20 15:31:19 CST 2016
     */
    public void setPhonenumber(String phonenumber) {
        this.phonenumber = phonenumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.EMAIL
     *
     * @return the value of user.EMAIL
     *
     * @mbggenerated Thu Oct 20 15:31:19 CST 2016
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.EMAIL
     *
     * @param email the value for user.EMAIL
     *
     * @mbggenerated Thu Oct 20 15:31:19 CST 2016
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.STATUS
     *
     * @return the value of user.STATUS
     *
     * @mbggenerated Thu Oct 20 15:31:19 CST 2016
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.STATUS
     *
     * @param status the value for user.STATUS
     *
     * @mbggenerated Thu Oct 20 15:31:19 CST 2016
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.TOKEN
     *
     * @return the value of user.TOKEN
     *
     * @mbggenerated Thu Oct 20 15:31:19 CST 2016
     */
    public String getToken() {
        return token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.TOKEN
     *
     * @param token the value for user.TOKEN
     *
     * @mbggenerated Thu Oct 20 15:31:19 CST 2016
     */
    public void setToken(String token) {
        this.token = token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.LOCATION_ID
     *
     * @return the value of user.LOCATION_ID
     *
     * @mbggenerated Thu Oct 20 15:31:19 CST 2016
     */
    public String getLocationId() {
        return locationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.LOCATION_ID
     *
     * @param locationId the value for user.LOCATION_ID
     *
     * @mbggenerated Thu Oct 20 15:31:19 CST 2016
     */
    public void setLocationId(String locationId) {
        this.locationId = locationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.CITY
     *
     * @return the value of user.CITY
     *
     * @mbggenerated Thu Oct 20 15:31:19 CST 2016
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.CITY
     *
     * @param city the value for user.CITY
     *
     * @mbggenerated Thu Oct 20 15:31:19 CST 2016
     */
    public void setCity(String city) {
        this.city = city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.DISTRICT
     *
     * @return the value of user.DISTRICT
     *
     * @mbggenerated Thu Oct 20 15:31:19 CST 2016
     */
    public String getDistrict() {
        return district;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.DISTRICT
     *
     * @param district the value for user.DISTRICT
     *
     * @mbggenerated Thu Oct 20 15:31:19 CST 2016
     */
    public void setDistrict(String district) {
        this.district = district;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.ADDRESS
     *
     * @return the value of user.ADDRESS
     *
     * @mbggenerated Thu Oct 20 15:31:19 CST 2016
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.ADDRESS
     *
     * @param address the value for user.ADDRESS
     *
     * @mbggenerated Thu Oct 20 15:31:19 CST 2016
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.COUNTRY
     *
     * @return the value of user.COUNTRY
     *
     * @mbggenerated Thu Oct 20 15:31:19 CST 2016
     */
    public String getCountry() {
        return country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.COUNTRY
     *
     * @param country the value for user.COUNTRY
     *
     * @mbggenerated Thu Oct 20 15:31:19 CST 2016
     */
    public void setCountry(String country) {
        this.country = country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.AVATAR
     *
     * @return the value of user.AVATAR
     *
     * @mbggenerated Thu Oct 20 15:31:19 CST 2016
     */
    public String getAvatar() {
        return avatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.AVATAR
     *
     * @param avatar the value for user.AVATAR
     *
     * @mbggenerated Thu Oct 20 15:31:19 CST 2016
     */
    public void setAvatar(String avatar) {
        this.avatar = avatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.REAL_NAME
     *
     * @return the value of user.REAL_NAME
     *
     * @mbggenerated Thu Oct 20 15:31:19 CST 2016
     */
    public String getRealName() {
        return realName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.REAL_NAME
     *
     * @param realName the value for user.REAL_NAME
     *
     * @mbggenerated Thu Oct 20 15:31:19 CST 2016
     */
    public void setRealName(String realName) {
        this.realName = realName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.ROLE_ID
     *
     * @return the value of user.ROLE_ID
     *
     * @mbggenerated Thu Oct 20 15:31:19 CST 2016
     */
    public Long getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.ROLE_ID
     *
     * @param roleId the value for user.ROLE_ID
     *
     * @mbggenerated Thu Oct 20 15:31:19 CST 2016
     */
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }
}